# application.yml (공통 설정)
spring:
  # 활성 프로파일 설정(기본값:local)
  profiles:
    active: local
  # 애플리케이션 이름 설정
  application:
    name: cicd_demo

# 모니터링 및 메트릭스 설정
management:
  #Actuator 엔드포인트 설정
  endpoints:
    web:
      # 노출할 엔드포인트 설정
      exposure:
        include: health,metrics,prometheus
      # Actuator 기본 경로 설정(/actuator)
      base-path: /actuator
  # 상태 체크 엔드포인트 설정
  endpoint:
    health:
      # 쿠버네티스 프로브 활성화
      probes:
        enabled: true
  # 메트릭스 설정
  metrics:
    # 메트릭스 태그 설정
    tags:
      # 애플리케이션 이름 태그
      application: ${spring.application.name}
      # 환경 태그(기본값 : dev)
      environment: ${spring.profiles.active:dev}
    # 메트릭스 활성화 설정
    enable:
      # JVM 메트릭스 활성화 
      jvm: true
      #프로세서 메트릭스 활성화
      process: true
      # 시스템 메트릭스 활성화
      system: true
  #프로메테우스 설정
  prometheus:
    #프로메테우스 메트릭스 설정
    metrics:
      #메트릭스 익스포트 활성화
      export:
        enabled: true
